import { Inter } from "next/font/google";
import "./globals.css";
import AppBar from "./app-bar/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Program-Viewer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppBar />
        {children}
      </body>
    </html>
  );
}
